### ISSUE TITLE
Rename 'parse' tests to 'syntax' tests

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-tests#16]
Perhaps a more apt name for the tests checking for a syntax error in a PartiQL statement could be `syntax` rather than `parse` as that's what's ultimately being tested.

Would involve renaming the following:
- directory for test category
- test annotation and assertions
- ISL schema
- (for test runners, rename parse -> syntax)

**Comment by am357** [comment]
As a follow-up, following the discussion I and @jpschorr recently had, we also likely need to check the current parse tests and see which one can be removed from syntax tests, e.g. [this `IS` fail test](https://github.com/partiql/partiql-tests/blob/main/partiql-test-data/fail/parser/primitives/operators/is-operator.ion#L11) should not fail for syntax test, under the assumption that we consider `IS <expr>` a valid syntax which can then gets weeded out by a further pass.

**Comment by alancai98** [comment]
> As a follow-up, following the discussion I and @jpschorr recently had, we also likely need to check the current parse tests and see which one can be removed from syntax tests, e.g. [this `IS` fail test](https://github.com/partiql/partiql-tests/blob/main/partiql-test-data/fail/parser/primitives/operators/is-operator.ion#L11) should not fail for syntax test, under the assumption that we consider `IS <expr>` a valid syntax which can then gets weeded out by a further pass.

Agreed on that test. It's more of a semantic failure. I'll change in an upcoming PR.

Also based on some of the comments in https://github.com/partiql/partiql-tests/pull/15, may also rename `Semantic` to `StaticAnalysis` since `Semantic` could be pretty vague.
